builders:
  path_builder:
    import: "package:frouter/builder/builder.dart"
    builder_factories: [ "pathBuilder" ]
    build_extensions: { ".dart": [ ".g.part" ] }
    runs_before: [ ":map_builder" ]
    auto_apply: dependents #none，dependents，root_package，all_packages
    build_to: cache # source, cache

  router_register_builder:
    import: "package:frouter/builder/builder.dart"
    builder_factories: [ "routerRegisterBuilder" ]
    build_extensions: { ".dart": [ ".router" ] }
    runs_before: [ ":map_builder" ]
    applies_builders:
      - frouter:map_builder
    auto_apply: dependents #none，dependents，root_package，all_packages
    build_to: cache # source, cache

  router_task_builder:
    import: "package:frouter/builder/builder.dart"
    builder_factories: [ "routerTaskBuilder" ]
    build_extensions: { ".dart": [ ".task" ] }
    runs_before: [ ":task_builder" ]
    applies_builders:
      - frouter:task_builder
    auto_apply: dependents #none，dependents，root_package，all_packages
    build_to: cache # source, cache

post_process_builders:
  map_builder:
    import: "package:frouter/builder/builder.dart"
    builder_factory: mapPostProcessBuilder

  task_builder:
    import: "package:frouter/builder/builder.dart"
    builder_factory: taskPostBuilder


