// Generated by lwlizhe frouter plugin, do not edit manually.
// run pub run build_runner build --delete-conflicting-outputs
// ignore_for_file: directives_ordering
// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:frouter/bin/entity/frouter_router_map.dart' as _i1;
import 'package:frouter/bin/builder/frouter_widget_builder.dart' as _i2;
import 'package:flutter/material.dart' as _i3;
import 'package:module_a/module_a_route_export.dart' as _i4;
import 'package:module_a/entity/user_info.dart' as _i5;
import 'package:frouter/bin/helper/safety_parameter_transform_utils.dart'
    as _i6;

class FModuleRouterMap extends _i1.FRouterRouterMap {
  @override
  String get hostRouterGroup {
    return 'example';
  }

  @override
  String get currentRouterGroup {
    return 'module_a';
  }

  @override
  List<_i1.FRouterRouterMap> get subModule {
    return [];
  }

  @override
  Map<String, _i2.FRouterWidgetBuilder> get routerMap {
    return <String, _i2.FRouterWidgetBuilder>{
      'user/user_info':
          (_i3.BuildContext context, Map<String, String>? parameters) {
        return _i4.UserInfoPage(
          userInfo: _i5.UserInfo(
            name: _i6.transform<String>(parameters?['name']) as String,
          ),
          userToken: _i6.transform<String>(parameters?['userTokenA']) as String,
        );
      },
    };
  }

  @override
  Map<String, _i2.FRouterProviderBuilder> get providerMap {
    return <String, _i2.FRouterProviderBuilder>{};
  }
}
